# Setup
setup: simclr

# Model
backbone: alexnet
model_kwargs:
   num_heads: 40
   features_dim: 128
img_size: 128

# Dataset
train_db_name: CelebA
val_db_name: CelebA
num_classes: 40
criterion_loss: vloss

# Loss
criterion: simclr
criterion_kwargs:
   temperature: 0.07

# Hyperparameters
optimizer: sgd
optimizer_kwargs:
   nesterov: False
   weight_decay: 0.0001 
   momentum: 0.9
   lr: 0.04
scheduler: cosine
scheduler_kwargs:
   lr_decay_rate: 0.1
num_workers: 8

# Transformations
augmentation_strategy: ours 
augmentation_kwargs:
   crop_size: 128
   normalize:
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]
   num_strong_augs: 4
   cutout_kwargs:
     n_holes: 1
     length: 16
     random: True

waugmentation_kwargs:
   random_resized_crop:
      size: 128
      scale: [0.2, 1.0]
   color_jitter_random_apply:
      p: 0.8
   color_jitter:
      brightness: 0.4
      contrast: 0.4
      saturation: 0.4
      hue: 0.1
   random_grayscale: 
      p: 0.2
   normalize:
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]

transformation_kwargs:
   crop_size: 128
   normalize:
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]
